- name: Install YubiKey Software
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - gnupg2
    - gnupg-agent
    - scdaemon
    - pcscd
    - yubikey-personalization
    - libusb-1.0-0-dev

- name: Create GPG Directory
  file:
    path: /home/dan/.gnupg
    state: directory

- name: Copy GPG Config
  copy:
    src: ./files/desktop/gpg/gpg.conf
    dest: /home/dan/.gnupg/gpg.conf
    owner: dan
    group: dan
    mode: 0700
- name: Copy GPG-Agent Config
  copy:
   src: ./files/desktop/gpg/gpg-agent.conf
   dest: /home/dan/.gnupg/gpg-agent.conf
   owner: dan
   group: dan
   mode: 0644

- name: Get GPG Public Keys
  command: gpg --keyserver eu.pool.sks-keyservers.net --recv "{{ item }}"
  with_items:
    - D5236EF584F708EE

- name: Trust GPG Public Keys
  command: gpg --import-ownertrust ./files/desktop/gpg/trust

- name: Copy .bashrc
  copy:
    src: ./files/desktop/bashrc
    dest: /home/dan/.bashrc
    owner: dan
    group: dan
    mode: 0755
