- name: Copy Grub Config
  copy:
    src: ./files/desktop/grub
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0644
- name: Update Grub
  become: yes
  become_user: root
  command: update-grub