- name: Install Desktop Packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - i3
    - xinit
    - xorg
    - xserver-xorg
    - mesa-utils
    - mesa-utils-extra
    - rofi
    - xautolock
    - feh
    - fonts-noto-color-emoji
    - xfce4-power-manager
    - libnotify-bin
    - jq

- name: Install .deb packages
  apt:
    deb: "{{ item }}"
  with_items:
    - https://github.com/acrisci/playerctl/releases/download/v0.6.1/playerctl-0.6.1_amd64.deb

- name: Create config directories
  file: path=/home/dan/{{ item }} state=directory
  with_items:
    - .config
    - .config/i3
    - .config/i3status
    - .config/rofi
    - .screenlayout

- name: Copy config from repo
  copy:
    src: ./files/desktop/{{ item }}
    dest: /home/dan/.config/{{ item }}
    owner: dan
    group: dan
    mode: 0644
  with_items:
    - i3/config
    - i3/desktop.png
    - i3status/config
    - rofi/config

- name: Copy scripts for i3
  copy:
    src: ./files/desktop/{{ item }}
    dest: /home/dan/.config/{{ item }}
    owner: dan
    group: dan
    mode: 0744
  with_items:
    - i3/pranklock.sh
    - i3/pranklock2.sh
    - i3/swap.sh

- name: Copy screenlayouts
  copy:
    src: "{{ item }}"
    dest: /home/dan/.screenlayout
    owner: dan
    mode: 744
  with_fileglob:
    - ./files/desktop/screenlayout/*.sh
- name: Install Build Things
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - automake
    - autoconf
    - make
    - gcc
 
- name: Clone Light Repo
  git:
    repo: "https://github.com/haikarainen/light.git"
    dest: ~/.config/light
    clone: yes

- name: Install Light
  command: "{{ item }}"
  args:
    chdir: ~/.config/light
  become: yes
  become_user: root
  with_items:
    - ./autogen.sh
    - ./configure && make
    - make install
