- name: Install Desktop Packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - i3
    - xinit
    - xorg
    - xserver-xorg
    - mesa-utils
    - mesa-utils-extra
    - rofi
    - xautolock
    - feh
    - fonts-noto-color-emoji
    - wicd
    - xfce4-power-manager

- name: Create config directories
  file: path=/home/dan/{{ item }} state=directory
  with_items:
    - .config
    - .config/i3
    - .config/i3status
    - .config/rofi
    - .screenlayout

- name: Copy config from repo
  copy:
    src: ./files/desktop/{{ item }}
    dest: /home/dan/.config/{{ item }}
    owner: dan
    group: dan
    mode: 0644
  with_items:
    - i3/config
    - i3/pranklock.sh
    - i3/pranklock2.sh
    - i3/desktop.png
    - i3status/config
    - rofi/config

- name: Install Build Things
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - automake
    - autoconf
    - make
    - gcc
 
- name: Clone Light Repo
  git:
    repo: "https://github.com/haikarainen/light.git"
    dest: ~/.config/light
    clone: yes

- name: Install Light
  command: "{{ item }}"
  args:
    chdir: ~/.config/light
  with_items:
    - ./autogen.sh
    - ./configure && make
    - sudo make install
