- name: Install Desktop Packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - i3
    - xinit
    - xorg
    - xserver-xorg
    - mesa-utils
    - mesa-utils-extra
    - rofi
    - xautolock
    - feh

- name: Create config directories
  file: path=/home/dan/{{ item }} state=directory
  with_items:
    - .config
    - .config/i3
    - .config/i3status
    - .config/rofi

- name: Copy i3 config from repo
  copy:
    src: ./files/desktop/i3/{{ item }}
    dest: /home/dan/.config/i3/{{ item }}
    owner: dan
    group: dan
    mode: 0644
  with_items:
    - config
    - pranklock.sh
    - pranklock2.sh
    - desktop.png

- name: Copy i3status config from repo
  copy:
    src: ./files/desktop/i3status-config
    dest: /home/dan/.config/i3status/config
    owner: dan
    group: dan
    mode: 0644
- name: Copy rofi config from repo
  copy:
    src: ./files/desktop/rofi-config
    dest: /home/dan/.config/rofi/config
    owner: dan
    group: dan
    mode: 0644

