- name: Install Desktop Packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - i3
    - xinit
    - xorg
    - xserver-xorg
    - mesa-utils
    - mesa-utils-extra
    - rofi
    - xautolock
    - feh
    - fonts-noto-color-emoji

- name: Create config directories
  file: path=/home/dan/{{ item }} state=directory
  with_items:
    - .config
    - .config/i3
    - .config/i3status
    - .config/rofi
    - .screenlayout

- name: Copy config from repo
  copy:
    src: ./files/desktop/{{ item }}
    dest: /home/dan/.config/{{ item }}
    owner: dan
    group: dan
    mode: 0644
  with_items:
    - i3/config
    - i3/pranklock.sh
    - i3/pranklock2.sh
    - i3/desktop.png
    - i3status/config
    - rofi/config

- name: Copy screenlayouts
  copy:
    src: ./files/desktop/screenlayout
    dest: /home/dan/.screenlayout
    user: dan
    group: dan
    mode: 0644
