- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - import_tasks: tasks/misc/remove-unwanted-server.yml
    - import_tasks: tasks/desktop/arandr.yml
    - import_tasks: tasks/desktop/i3.yml
    - import_tasks: tasks/utilities/git.yml
