- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - import_tasks: tasks/os/ubuntu-server-1804.yml
    - import_tasks: tasks/desktop/i3.yml
    - import_tasks: tasks/apps/code.yml
    - import_tasks: tasks/apps/utilities.yml
