- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - import_tasks: tasks/os/ubuntu-server-1804.yml
    - import_tasks: tasks/hw/xps-15-9560.yml
    - import_tasks: tasks/desktop/i3.yml
    - import_tasks: tasks/desktop/lightdm.yml
    - import_tasks: tasks/desktop/plymouth.yml
    - import_tasks: tasks/desktop/gpg.yml
    - import_tasks: tasks/desktop/media.yml
    - import_tasks: tasks/apps/code.yml
    - import_tasks: tasks/apps/general.yml
    - import_tasks: tasks/apps/pass.yml
    - import_tasks: tasks/apps/utilities.yml
    - import_tasks: tasks/personal/dirs.yml
    - import_tasks: tasks/cleanup/apps.yml
