- name: Install Code Applications
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - git
    - vim
    
- name: Setup Git
  git_config:
    scope: global
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    "user.email": "dan@trickey.io"
    "user.name": "Dan Trickey"
    "commit.gpgsign": true
