- name: Install Code Applications
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - git
    - vim
- name: Setup Git
  command: "{{ item }}"
  with_items:
    - git config --global user.email "dan@trickey.io"
    - git config --global user.name "Dan Trickey"
