- name: Install General Desktop Programs
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - chromium-browser
    - chromium-ublock-origin
    - steam
    - vlc
- name: Install General Desktop Snaps
  become: yes
  become_user: root
  command: "snap install {{ item }}" 
  with_items:
    - mailspring
    - slack --classic
    - vscode --classic
    - spotify
    - slack --classic
    - intellij-idea-ultimate --classic
    - pycharm-professional --classic
    - phpstorm --classic
    - inkscape
